# Generated by Django 5.0.3 on 2024-04-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utilities", "0002_alter_categorygroup_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoggerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("Error", "Error"),
                            ("Warning", "Warning"),
                            ("Normal", "Normal"),
                            ("Admin Notice", "Severe Issue"),
                        ],
                        default="Normal",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("has_been_viewed", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TrackingIncrementor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(blank=True, default=0)),
                ("max_field_len", models.IntegerField(blank=True, default=2000000000)),
                ("times_incremented", models.IntegerField(blank=True, default=0)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
