# Generated by Django 5.0.3 on 2024-04-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utilities", "0003_loggermodel_trackingincrementor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_date", models.DateField()),
                ("req_time", models.TimeField()),
                ("set_date", models.DateField(blank=True, null=True)),
                ("set_time", models.TimeField(blank=True, null=True)),
                ("client_name", models.CharField(max_length=250)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("has_been_viewed", models.BooleanField(blank=True, default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
