# Generated by Django 5.0.3 on 2024-03-26 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=150)),
                (
                    "client_email",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "client_social",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("style_description", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="portfolio/")),
                ("img_description", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now=True, null=True)),
                (
                    "img_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stylist_portfolio.imagegroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="imagegroup",
            name="imgs",
            field=models.ManyToManyField(blank=True, to="stylist_portfolio.imageitem"),
        ),
    ]
